
version: '2'

services:
  pg-master:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    networks:
     - postgresql-network
    ports:
     - "127.0.0.2:5432:5432"

  pg-slave:
    build: '.'
    image: 'danieldent/postgres-replication'
    restart: 'always'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql/data'
    networks:
     - postgresql-network
    ports:
     - "127.0.0.3:5432:5432"
    links:
     - 'pg-master'
networks:
    postgresql-network: